services:

  postgres:
    image: postgres:17
    container_name: postgres-bank-mov

    environment:
      POSTGRES_DB: bankmovdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  bank-api:

    build: .

    container_name: bank-api-mov

    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"